-- Logs
SELECT COUNT(1) FROM OpsDb.dbo.ServerEventNotificationLog WITH(NOLOCK)
SELECT COUNT(1) FROM [dbo].[LOG] WITH(NOLOCK) 

-- Current status
SELECT COUNT(1) FROM [dbo].[ADDRESS_BOOK_ENTRY_XML_TEMP_STORAGE]		WITH(NOLOCK) 
SELECT COUNT(1) FROM [dbo].[XML_TEMP_STORAGE_ID_TO_ADDRESS_BOOK_ID_MAP]		WITH(NOLOCK) 
SELECT COUNT(1) FROM [dbo].[ADDRESS_BOOK_ENTRY_PARSED]		WITH(NOLOCK) 
SELECT COUNT(1) FROM [dbo].[ADDRESS_BOOK_ACTION_INITIATOR]		WITH(NOLOCK) 
SELECT COUNT(1) FROM [dbo].[ADDRESS_BOOK_ACTION_TARGET]		WITH(NOLOCK) 
SELECT COUNT(1) FROM [dbo].[ADDRESS_BOOK_ENTRY_ACTION_INITIATOR]		WITH(NOLOCK) 
SELECT COUNT(1) FROM [dbo].[ADDRESS_BOOK_ENTRY_ACTION_TARGET]		WITH(NOLOCK) 
SELECT COUNT(1) FROM [dbo].[ADDRESS_BOOK_ENTRY_XML_ACTION_INITIATOR]		WITH(NOLOCK) 
SELECT COUNT(1) FROM [dbo].[ADDRESS_BOOK_ENTRY_XML_ACTION_TARGET]		WITH(NOLOCK) 